### ISSUE TITLE
Theme Errors when installed through Admin interface

### ISSUE THREAD

**Issue by AmasaDelano** [AkazieIT/grav-theme-akazie-wood#11]
**PROBLEM:**

Theme shows an error when installed through the admin plugin (and possibly other ways, I only tried through the admin plugin).

**REPRODUCE:**

1. Install Grav v1.7.14 with the Admin Plugin v1.10.14, downloadable [here](https://getgrav.org/download/core/grav-admin/1.7.14).
2. Go to the admin page at `/admin`. Create a user and log in.
3. Go to the "Themes" section and click "+Add" in the top right.
4. Search for "akazie" and install the "Akazie Wood" theme, v0.9.950.
5. Go to "Themes" and Activate the Akazie Wood theme.
6. View the website's home page.

**EXPECTED:**

The home page should load normally.

**ACTUAL:**

This error message was displayed:
![error message](https://imgpile.com/images/7ZmOtg.png)

**OTHER NOTES:**

The error was fixed by adding a file `custom.css` into the theme's `custom/css` folder. I think this file should either be made non-required, or should be included when the theme is installed.

Thanks! :)

**Comment by grimnebluna** [comment]
hi. thanks for the info. will be fixed in 0.9.951 with additional instructions for custom.css
