### ISSUE TITLE
For what and how can I use catfilter & catpost? / disable google fonts?

### ISSUE THREAD

**Issue by emc6** [AkazieIT/grav-theme-akazie-wood#14]
Hi,

thank you for a beginner-friendly theme! Exactly what I needed.
I am trying to migrate my site to it and I found these two templates: catfilter and catpost.
For what can I use those? Could you share some insight? (nothing found on demo content)

And on https://github.com/AkazieIT/grav-theme-akazie-wood/issues/4#issue-596446933 buttle mentions to use other fonts. Is there a way to disable external fonts for the theme?

Thank you for your help.

**Comment by grimnebluna** [comment]
Hi

We accidentially pushed the catpost/catfilter modules (which are modules for a client) with the theme on the last few updates. They shouldn't be there :-)

They won't be pushed to new users, but they will remain in your installation. If you want a clean theme, you can remove the following files from your theme folder:

blueprints/catfilter.yaml
templates/catfilter.html.twig
blueprints/catpost.yaml
templates/catpost.html.twig

Sorry for the inconvenience
