### ISSUE TITLE
Copy Module Type Text page -> Page Type Catfilter page

### ISSUE THREAD

**Issue by emc6** [AkazieIT/grav-theme-akazie-wood#15]
Hi,

I got a main modular site and some sub modul text type sites.
With the three vertical dots, I use the copy page function on existing modul text site and created a new site.
The new site is not a module type text site, but a page type catfilter site.

Best regards

**Comment by grimnebluna** [comment]
Hi

We accidentially pushed the catpost/catfilter modules (which are modules for a client) with the theme on the last few updates. They shouldn't be there :-)

They won't be pushed to new users, but they will remain in your installation. If you want a clean theme, you can remove the following files from your theme folder:

blueprints/catfilter.yaml
templates/catfilter.html.twig
blueprints/catpost.yaml
templates/catpost.html.twig

Sorry for the inconvenience

Concerning your particular problem: you can choose the module or page template you need in your duplicated module under the tab "advanced"
