### ISSUE TITLE
Error adding modular page type Breaktitle

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [AkazieIT/grav-theme-akazie-wood#17]
Hi.
When I try to add a Breaktitle module in a modular page, I obtain this error:

ERROR: modular/catfilter.html.twig template not found for page:

It seems that catfilter.html.twig doesn't exist in modular folder.

**Comment by grimnebluna** [comment]
It seems like this is a bug from an old akazie-wood version. did you try to update your theme? Which akazie-wood version are you running?

**Comment by pmoreno-rodriguez** [comment]
Hi.
I've updated the theme and seems the error has dissapeared, but why there are two blueprints templates (catfilter and catposts) without their twig templates?

**Comment by grimnebluna** [comment]
Those templates got pushed by accident with a past update and won't get deleted automatically. you can delete them if you like. won't affect your theme.
