### ISSUE TITLE
Changing main image

### ISSUE THREAD

**Issue by triszterer** [AkazieIT/grav-theme-akazie-wood#23]
I would like to change main image by replacing /user/themes/akazie-wood/images/home.jpg but there is no effect. Can you tell me the solution?

**Comment by grimnebluna** [comment]
try rebuilding the cache. or you could set the image globally on every container page: 

![image](https://github.com/AkazieIT/grav-theme-akazie-wood/assets/20042071/b78a86af-18a3-4644-b28a-ce9b331ea738)
