### ISSUE TITLE
Not buildable with node 18 on Windows

### ISSUE THREAD

**Issue by JonasTrampe** [AkazieIT/grav-theme-akazie-wood#24]
Hej,

is there any chance that the node dependencies could be upgraded?
The old gyp version doesn't work with newer node versions.

npm ERR!   File "C:\Users\riagan\.node-gyp\18.16.1\include\node\common.gypi", line 1
npm ERR!     e_data_file_flag%': 1
npm ERR!                         ^
npm ERR! SyntaxError: EOL while scanning string literal
npm ERR! gyp ERR! configure error

**Comment by grimnebluna** [comment]
we will soon sunset akazie wood. please use a node version manager. sorry for the inconvenience
