### ISSUE TITLE
validator.w3.org reports errors

### ISSUE THREAD

**Issue by zieren** [AkazieIT/grav-theme-akazie-wood#26]
For [a page I recently set up](https://schlafhilfe-muenchen.org) I'm getting validation errors for instances of this code:

```
<a href="/hilfreiches" class="" link>
```

The error is:

```
Error: Attribute "link" not allowed on element <a> at this point.
```

The same errors are reported for https://demo.akazie.com/akazie-wood/, plus a complaint about using `|` in the Google fonts URL (which I replaced with `%7C` on my page).

Of course everything still renders fine, but maybe a validator run should be part of the release process?

**Comment by grimnebluna** [comment]
Sorry, we are currently only doing crucial updates to Akazie Wood since we will soon release a new theme. Feel free to fork the theme!
