### ISSUE TITLE
Optinal visibility of modules in a modular page

### ISSUE THREAD

**Issue by derjoergbode** [AkazieIT/grav-theme-akazie-wood#27]
Hello everyone,
many thanks for this easy to use and expandable theme. I like to work with it for simple and fast websites.

I would like to know if it is possible to make modules invisible, or better still to activate or deactivate them on a time-controlled basis. I know this function from other themes and would like to use it to display parts of the website only in a certain time window.

**Comment by grimnebluna** [comment]
Will be a feature of our new theme Akazie Forest
