### ISSUE TITLE
google maps

### ISSUE THREAD

**Issue by buttle** [AkazieIT/grav-theme-akazie-wood#4]
Hi,

What an amazing theme!! Thank you :)

We don't use google maps, in fact, we don't use anything GAFAM. That means google fonts and maps too.

You include an option to load the fonts from somewhere else, so that's good. Less tracking google can do on our visitors!

Instead of google maps we use Open street maps, (that I suppose I can include with an iframe). But...

Requests to google are made from map-js.html.twig. It would be a bonus if those requests were only made if the admin supplies the map API, or something like that. As it is, I will manually delete the content of map-js, and remember to do it after each update.

Anyway. Thank you once again.

**Comment by Memurame** [comment]
![Osm](https://user-images.githubusercontent.com/15847494/79458743-8b0e3a00-7ff2-11ea-9a58-9b12aa72afe4.PNG)
Now it is possible to use Open Street Map. You can now set the map of your choice in the theme settings.

Wait for next update.

**Comment by buttle** [comment]
Thank you very much! :)

I had install [Map marker leaflet](https://github.com/finanalyst/grav-plugin-map-marker-leaflet) works great, but even better if you have things working out of the box!

Cheers.
